pipeline {
    agent any
    environment {
        POSTGRES_SECRET_USR = credentials('postgres_user')
        POSTGRES_SECRET_PSW = credentials('postgres_password')
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv .venv'
                sh '. .venv/bin/activate && pip install -r "PyTest DQ Framework/requirements.txt"'
            }
        }

        stage('Run DQ Checks Script') {
            steps {
                sh '''
                . .venv/bin/activate
                export PYTHONPATH=$PYTHONPATH:"$WORKSPACE/PyTest DQ Framework"
                python "PyTest DQ Framework/scripts/run_dq_checks.py"
                '''
            }
        }

        stage('Run Pytests') {
            steps {
                sh '''
                . .venv/bin/activate
                export PYTHONPATH=$PYTHONPATH:"$WORKSPACE/PyTest DQ Framework"
                pytest "PyTest DQ Framework/tests" --html=html_report/report.html
                '''
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
            }
        }
    }
}
