pipeline {
    agent any

    environment {
        POSTGRES_SECRET_USR = credentials('postgres_user')
        POSTGRES_SECRET_PSW = credentials('postgres_password')
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv .venv
                    . .venv/bin/activate
                    .venv/bin/pip install --upgrade pip
                    .venv/bin/pip install -r "PyTest DQ Framework/requirements.txt"
                '''
            }
        }

        stage('Run DQ Checks Script') {
            steps {
                sh '''
                    . .venv/bin/activate
                    export PYTHONPATH="$PYTHONPATH:$(pwd)/PyTest DQ Framework"

                    .venv/bin/python "PyTest DQ Framework/scripts/run_dq_checks.py"
                '''
            }
        }

        stage('Run Pytests') {
            steps {
                sh '''
                    . .venv/bin/activate
                    export PYTHONPATH="$PYTHONPATH:$(pwd)/PyTest DQ Framework"

                    .venv/bin/pytest "PyTest DQ Framework/tests" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user="$POSTGRES_SECRET_USR" \
                        --db_password="$POSTGRES_SECRET_PSW" \
                        --html=html_report/report.html
                '''
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
            }
        }
    }
}
